# Generated by Django 2.2.5 on 2020-04-01 03:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=256)),
            ],
            managers=[
                ('noticias', django.db.models.manager.Manager()),
            ],
        ),
    ]
