# Generated by Django 2.2.5 on 2020-04-03 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0003_auto_20200402_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
