# Generated by Django 2.2.5 on 2020-04-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0004_contacto_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
