# Generated by Django 2.2.5 on 2020-04-03 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0007_auto_20200403_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadistica',
            old_name='casos_Q1',
            new_name='casos_Chile',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='casos_Q2',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='casos_Q3',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='casos_Q4',
        ),
        migrations.AddField(
            model_name='estadistica',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
