# Generated by Django 2.2.5 on 2020-04-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0008_auto_20200403_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadistica',
            name='casos_Chile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='hospital_T1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='hospital_T2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='hospital_T3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='hospital_T4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='hospital_contagios',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='hospital_lm',
            field=models.IntegerField(),
        ),
    ]
