# Generated by Django 2.2.5 on 2020-04-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0009_auto_20200404_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='noticias/%Y/%m/%d/'),
        ),
    ]
