# Generated by Django 2.2.5 on 2020-04-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0012_auto_20200405_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadistica',
            old_name='hospital_lm',
            new_name='hospital_recuperados',
        ),
    ]
