# Generated by Django 2.2.5 on 2020-04-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0014_auto_20200407_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Archivo'), (1, 'Flujograma'), (2, 'Video')], default=0),
        ),
    ]
