# Generated by Django 2.2.5 on 2020-05-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0015_auto_20200407_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrato',
            field=models.IntegerField(choices=[(1, 'CONTRATA'), (2, 'HONORARIO'), (3, 'OTRO')], default=3),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='actividad',
            field=models.IntegerField(choices=[(1, 'Médico'), (2, 'Profesional de la Salud'), (3, 'Técnico de la Salud'), (4, 'Administrativo')], default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='servicio',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
