# Generated by Django 2.2.5 on 2020-05-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0016_auto_20200516_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrato',
            field=models.IntegerField(choices=[(1, 'Contrata'), (2, 'Honorario'), (3, 'Otro')], default=3),
        ),
    ]
