# Generated by Django 2.2.5 on 2020-05-16 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0017_auto_20200516_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
