# Generated by Django 2.2.5 on 2020-05-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0018_documento_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadistica',
            old_name='hospital_recuperados',
            new_name='funcionarios_PCR',
        ),
        migrations.RenameField(
            model_name='estadistica',
            old_name='hospital_contagios',
            new_name='funcionarios_contagiados',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='contagios_Chile',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='hospital_BASICA',
        ),
        migrations.RemoveField(
            model_name='estadistica',
            name='hospital_UPC',
        ),
    ]
